apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: huggingface-runtime
  namespace: default
spec:
  supportedModelFormats:
    - name: huggingface
      version: "1"
  containers:
    - name: huggingface
      image: kserve/huggingfaceserver:latest
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: grpc
          containerPort: 8081
          protocol: TCP
      env:
        - name: HF_HUB_DISABLE_TELEMETRY
          value: "1"
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "500m"
          memory: 1Gi
