apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: huggingface-runtime
  namespace: ai4bharat-serving
spec:
  supportedModelFormats:
  - name: huggingface
    version: "1"
  containers:
  - name: huggingface
    image: kserve/huggingfaceserver:latest
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "1"
        memory: 2Gi
    ports:
    - containerPort: 8080
      name: http
    - containerPort: 8081
      name: grpc
    env:
    - name: SAFETENSORS_FAST_GPU
      value: "1"
    - name: HF_HUB_DISABLE_TELEMETRY
      value: "1"
