apiVersion: v1
kind: Namespace
metadata:
  name: kserve
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve
  namespace: kserve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "pods", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["serving.knative.dev"]
  resources: ["services", "revisions", "routes", "configurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["serving.kserve.io"]
  resources: ["inferenceservices", "servingruntimes", "clusterservingruntimes", "inferencegraphs", "batchers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling.knative.dev"]
  resources: ["podautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kserve
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kserve
subjects:
- kind: ServiceAccount
  name: kserve
  namespace: kserve
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserve-controller-manager
  namespace: kserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kserve-controller-manager
  template:
    metadata:
      labels:
        app: kserve-controller-manager
    spec:
      serviceAccountName: kserve
      containers:
      - name: manager
        image: kserve/kserve-controller:latest
        args:
        - --leader-elect
        - --metrics-bind-address=:8080
        - --health-probe-bind-address=:8081
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: health
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kserve-controller-manager-metrics-service
  namespace: kserve
  labels:
    control-plane: controller-manager
    app: kserve-controller-manager
spec:
  ports:
  - name: https-controller
    port: 8443
    targetPort: https-controller
  selector:
    control-plane: controller-manager
    app: kserve-controller-manager
