apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: labeled-huggingface-runtime
  namespace: default
  labels:
    app: huggingface-runtime
    runtime: huggingface
spec:
  supportedModelFormats:
    - name: huggingface
  containers:
    - name: huggingface
      image: kserve/huggingfaceserver:latest
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: grpc
          containerPort: 8081
          protocol: TCP
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "500m"
          memory: 1Gi
